### ISSUE TITLE
test.py报错No module named 'event_representations'

### ISSUE THREAD

**Issue by YU2024DW** [HarmoniaLeo/FRLW-EvD#8]
您好，我在按照步骤运行到test.py文件时，报错ModuleNotFoundError: No module named 'event_representations'，这该如何解决呢

**Comment by YU2024DW** [comment]
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from core.exp import basicExp, tafExp, yolov3, yolox, tafBFMExp, yolov3tafBFM, yoloxtafBFM
  File "C:\Users\Administrator\Desktop\FRLW-EvD-main\core\exp.py", line 14, in <module>
    from data.fetcher import fetcherTrain, fetcherVal
  File "C:\Users\Administrator\Desktop\FRLW-EvD-main\data\fetcher.py", line 2, in <module>
    import event_representations as er
ModuleNotFoundError: No module named 'event_representations'
![微信图片_20240315105628](https://github.com/HarmoniaLeo/FRLW-EvD/assets/162982020/6ceeed35-608d-4f02-9b79-d7b29db12b56)
